# Generated by Django 5.1.7 on 2025-04-12 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_delete_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
