# Generated by Django 5.2 on 2025-05-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_user_alter_task_completion_time_userdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
